default:
    just --list

lab1:
    mvn compile --quiet && mvn exec:java -Dexec.mainClass=lab1.Main --quiet
    
lab1-personal:
    mvn compile --quiet && mvn exec:java -Dexec.mainClass=lab1_personal.Main --quiet

lab2:
    mvn compile && mvn exec:java -Dexec.mainClass=lab2.Main

lab2-combo:
    mvn compile && mvn exec:java -Dexec.mainClass=lab2_combo.Main

lab2-personal:
    mvn compile && mvn exec:java -Dexec.mainClass=lab2_personal.LessonAddForm

migrate:
    mvn flyway:clean -Dflyway.cleanDisabled=false && mvn flyway:migrate 
